---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubez-app
spec:
  selector:
    matchLabels:
      app: kubez-app
  template:
    metadata:
      labels:
        app: kubez-app
    spec:
      containers:
      - name: kubez
        image: docker.io/middlewaregruppen/kubez:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 300m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 100Mi
...
---
apiVersion: v1
kind: Service
metadata:
  name: kubez
spec:
  type: NodePort
  selector:
    app: kubez-app
  ports:
  - nodePort: 31503
    port: 3000
    targetPort: 3000
...

