---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubez
spec:
  selector:
    matchLabels:
      app: kubez
  template:
    metadata:
      labels:
        app: kubez
    spec:
      containers:
      - name: kubez
        image: docker.io/middlewaregruppen/kubez:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
...
---
apiVersion: v1
kind: Service
metadata:
  name: kubez
spec:
  type: NodePort
  selector:
    app: kubez
  ports:
  - nodePort: 31503
    port: 3000
    targetPort: 3000
...
